var tscApp = tscApp || {};

tscApp.PATTERNS = {
	"Banded Iron": "banded_iron.svg",
	"Basement": "basement.svg",
	"Brackish": "brackish.svg",
	"Chalk": "chalk.svg",
	"Chert": "chert.svg",
	"Chroncolumn Unknown": "chroncolumn_unknown.svg",
	"Clayey Limestone": "clayey_limestone.svg",
	"Clayey Sandstone": "clayey_sandstone.svg",
	"Claystone": "claystone.svg",
	"Coal": "coal.svg",
	"Coarse-grained Clastics": "coarse-grained_clastics.svg",
	"Coarse-grained Sandstone": "coarse-grained_sandstone.svg",
	"Conglomerate": "conglomerate.svg",
	"Continental Marl": "continental_marl.svg",
	"Cs Light Yellow": "cs_light_yellow.svg",
	"Dolomite": "dolomite.svg",
	"Dolomitic Limestone": "dolomitic_limestone.svg",
	"Evaporite": "evaporite.svg",
	"Fine-grained Clastics": "fine-grained_clastics.svg",
	"Fine-grained Sandstone": "fine-grained_sandstone.svg",
	"Gap": "gap.svg",
	"Glacial Till": "glacial_till.svg",
	"Gneiss": "gneiss.svg",
	"Granitic": "granitic.svg",
	"Gypsiferous Claystone": "gypsiferous_claystone.svg",
	"Gypsum-anhydrite": "gypsum-anhydrite.svg",
	"Halite": "halite.svg",
	"Lacustrine": "lacustrine.svg",
	"Lava": "lava.svg",
	"Limestone": "limestone.svg",
	"Metavolcanics": "metavolcanics.svg",
	"Mixed Marine": "mixed_marine.svg",
	"No Data": "no_data.svg",
	"Oolitic Limestone": "oolitic_limestone.svg",
	"Pelagic Biogenic": "pelagic_biogenic.svg",
	"Pelagic Marl": "pelagic_marl.svg",
	"Reef Limestone": "reef_limestone.svg",
	"Saline": "saline.svg",
	"Sandstone": "sandstone.svg",
	"Sandy Claystone": "sandy_claystone.svg",
	"Sandy Limestone": "sandy_limestone.svg",
	"Shallow-marine Carbonate": "shallow-marine_carbonate.svg",
	"Shallow-marine Marl": "shallow-marine_marl.svg",
	"Siliceous Chalk": "siliceous_chalk.svg",
	"Siliceous Limestone": "siliceous_limestone.svg",
	"Siltstone": "siltstone.svg",
	"Soil": "soil.svg",
	"Volcanic Ash": "volcanic_ash.svg",
	"Volcanics": "volcanics.svg",
}