var tscApp = tscApp || {};

tscApp.PATTERNS = {'Cs Light Yellow': 'cs_light_yellow.svg',
 'Two Tone Red': 'two_tone_red.png',
 'Two Tone Olive Green': 'two_tone_olive_green.png',
 'Cs Dark Magenta': 'cs_dark_magenta.png',
 'Cs Medium Red': 'cs_medium_red.png',
 'Cs Dark Beige': 'cs_dark_beige.png',
 'Sandy Claystone': 'sandy_claystone.svg',
 'Clayey Sandstone': 'clayey_sandstone.svg',
 'Chert': 'chert.svg',
 'Shallow Marine Marl': 'shallow-marine_marl.svg',
 'Gap': 'gap.svg',
 'Conglomerate': 'conglomerate.svg',
 'Cs Light Gray': 'cs_light_gray.png',
 'Two Tone Gray': 'two_tone_gray.png',
 'Cs Medium Sea Green': 'cs_medium_sea_green.png',
 'Cs Light Pink': 'cs_light_pink.png',
 'Cs Medium Beige': 'cs_medium_beige.png',
 'Coal': 'coal.svg',
 'Cs Medium Navy': 'cs_medium_navy.png',
 'Cs Dark Gray': 'cs_dark_gray.png',
 'Volcanic Ash': 'volcanic_ash.svg',
 'Cs Dark Pink': 'cs_dark_pink.png',
 'Cs Medium Brown': 'cs_medium_brown.png',
 'Cs Medium Purple': 'cs_medium_purple.png',
 'Cs Dark Olive Green': 'cs_dark_olive_green.png',
 'Cs Medium Olive Green': 'cs_medium_olive_green.png',
 'Two Tone Beige': 'two_tone_beige.png',
 'Cs Dark Orange': 'cs_dark_orange.png',
 'Claystone': 'claystone.svg',
 'Sandstone': 'sandstone.svg',
 'Coarse Grained Clastics': 'coarse-grained_clastics.svg',
 'Halite': 'halite.svg',
 'Glacial Till': 'glacial_till.svg',
 'Basement': 'basement.svg',
 'Pelagic Biogenic': 'pelagic_biogenic.svg',
 'Cs Medium Yellow': 'cs_medium_yellow.png',
 'Evaporite': 'evaporite.svg',
 'Two Tone Blue': 'two_tone_blue.png',
 'Gypsum Anhydrite': 'gypsum-anhydrite.svg',
 'Lacustrine': 'lacustrine.svg',
 'Cs Dark Brown': 'cs_dark_brown.png',
 'Two Tone Red Green': 'two_tone_red_green.png',
 'Cs Dark Blue': 'cs_dark_blue.png',
 'Cs Light Blue': 'cs_light_blue.png',
 'Gneiss': 'gneiss.svg',
 'Soil': 'soil.svg',
 'Cs Light Purple': 'cs_light_purple.png',
 'Cs Light Navy': 'cs_light_navy.png',
 'Saline': 'saline.svg',
 'Clayey Limestone': 'clayey_limestone.svg',
 'Coarse Grained Sandstone': 'coarse-grained_sandstone.svg',
 'Cs Dark Yellow': 'cs_dark_yellow.png',
 'Sandy Limestone': 'sandy_limestone.svg',
 'Cs Medium Magenta': 'cs_medium_magenta.png',
 'Lava': 'lava.svg',
 'Cs Light Orange': 'cs_light_orange.png',
 'Metavolcanics': 'metavolcanics.svg',
 'Cs Light Sea Green': 'cs_light_sea_green.png',
 'No Data': 'no_data.svg',
 'Cs Medium Green': 'cs_medium_green.png',
 'Dolomite': 'dolomite.svg',
 'Cs Light Brown': 'cs_light_brown.png',
 'Cs Dark Sea Green': 'cs_dark_sea_green.png',
 'Cs Light Magenta': 'cs_light_magenta.png',
 'Chalk': 'chalk.svg',
 'Cs Light Green': 'cs_light_green.png',
 'Dolomitic Limestone': 'dolomitic_limestone.svg',
 'Cs Medium Pink': 'cs_medium_pink.png',
 'Chroncolumn Unknown': 'chroncolumn_unknown.svg',
 'Granitic': 'granitic.svg',
 'Oolitic Limestone': 'oolitic_limestone.svg',
 'Reef Limestone': 'reef_limestone.svg',
 'Cs Light Beige': 'cs_light_beige.png',
 'Cs Dark Green': 'cs_dark_green.png',
 'Volcanics': 'volcanics.svg',
 'Cs Medium Gray': 'cs_medium_gray.png',
 'Brackish': 'brackish.svg',
 'Cs Dark Purple': 'cs_dark_purple.png',
 'Siltstone': 'siltstone.svg',
 'Fine Grained Clastics': 'fine-grained_clastics.svg',
 'Shallow Marine Carbonate': 'shallow-marine_carbonate.svg',
 'Siliceous Limestone': 'siliceous_limestone.svg',
 'Cs Light Olive Green': 'cs_light_olive_green.png',
 'Pelagic Marl': 'pelagic_marl.svg',
 'Continental Marl': 'continental_marl.svg',
 'Cs Medium Blue': 'cs_medium_blue.png',
 'Mixed Marine': 'mixed_marine.svg',
 'Gypsiferous Claystone': 'gypsiferous_claystone.svg',
 'Cs Medium Orange': 'cs_medium_orange.png',
 'Cs Light Red': 'cs_light_red.png',
 'Limestone': 'limestone.svg',
 'Banded Iron': 'banded_iron.svg',
 'Cs Dark Red': 'cs_dark_red.png',
 'Fine Grained Sandstone': 'fine-grained_sandstone.svg',
 'Siliceous Chalk': 'siliceous_chalk.svg',
 'Cs Dark Navy': 'cs_dark_navy.png'}
