var tscApp = tscApp || {};

tscApp.PATTERNS = {
	'Banded Iron': 'banded_iron.svg',
	'Basement': 'basement.svg',
	'Brackish': 'brackish.svg',
	'Chalk': 'chalk.svg',
	'Chert': 'chert.svg',
	'Chroncolumn Unknown': 'chroncolumn_unknown.svg',
	'Clayey Limestone': 'clayey_limestone.svg',
	'Clayey Sandstone': 'clayey_sandstone.svg',
	'Claystone': 'claystone.svg',
	'Coal': 'coal.svg',
	'Coarse Grained Clastics': 'coarse-grained_clastics.svg',
	'Coarse Grained Sandstone': 'coarse-grained_sandstone.svg',
	'Conglomerate': 'conglomerate.svg',
	'Continental Marl': 'continental_marl.svg',
	'Cs Dark Beige': 'cs_dark_beige.png',
	'Cs Dark Blue': 'cs_dark_blue.png',
	'Cs Dark Brown': 'cs_dark_brown.png',
	'Cs Dark Gray': 'cs_dark_gray.png',
	'Cs Dark Green': 'cs_dark_green.png',
	'Cs Dark Magenta': 'cs_dark_magenta.png',
	'Cs Dark Navy': 'cs_dark_navy.png',
	'Cs Dark Olive Green': 'cs_dark_olive_green.png',
	'Cs Dark Orange': 'cs_dark_orange.png',
	'Cs Dark Pink': 'cs_dark_pink.png',
	'Cs Dark Purple': 'cs_dark_purple.png',
	'Cs Dark Red': 'cs_dark_red.png',
	'Cs Dark Sea Green': 'cs_dark_sea_green.png',
	'Cs Dark Yellow': 'cs_dark_yellow.png',
	'Cs Light Beige': 'cs_light_beige.png',
	'Cs Light Blue': 'cs_light_blue.png',
	'Cs Light Brown': 'cs_light_brown.png',
	'Cs Light Gray': 'cs_light_gray.png',
	'Cs Light Green': 'cs_light_green.png',
	'Cs Light Magenta': 'cs_light_magenta.png',
	'Cs Light Navy': 'cs_light_navy.png',
	'Cs Light Olive Green': 'cs_light_olive_green.png',
	'Cs Light Orange': 'cs_light_orange.png',
	'Cs Light Pink': 'cs_light_pink.png',
	'Cs Light Purple': 'cs_light_purple.png',
	'Cs Light Red': 'cs_light_red.png',
	'Cs Light Sea Green': 'cs_light_sea_green.png',
	'Cs Light Yellow': 'cs_light_yellow.svg',
	'Cs Medium Beige': 'cs_medium_beige.png',
	'Cs Medium Blue': 'cs_medium_blue.png',
	'Cs Medium Brown': 'cs_medium_brown.png',
	'Cs Medium Gray': 'cs_medium_gray.png',
	'Cs Medium Green': 'cs_medium_green.png',
	'Cs Medium Magenta': 'cs_medium_magenta.png',
	'Cs Medium Navy': 'cs_medium_navy.png',
	'Cs Medium Olive Green': 'cs_medium_olive_green.png',
	'Cs Medium Orange': 'cs_medium_orange.png',
	'Cs Medium Pink': 'cs_medium_pink.png',
	'Cs Medium Purple': 'cs_medium_purple.png',
	'Cs Medium Red': 'cs_medium_red.png',
	'Cs Medium Sea Green': 'cs_medium_sea_green.png',
	'Cs Medium Yellow': 'cs_medium_yellow.png',
	'Dolomite': 'dolomite.svg',
	'Dolomitic Limestone': 'dolomitic_limestone.svg',
	'Evaporite': 'evaporite.svg',
	'Fine Grained Clastics': 'fine-grained_clastics.svg',
	'Fine Grained Sandstone': 'fine-grained_sandstone.svg',
	'Gap': 'gap.svg',
	'Glacial Till': 'glacial_till.svg',
	'Gneiss': 'gneiss.svg',
	'Granitic': 'granitic.svg',
	'Gypsiferous Claystone': 'gypsiferous_claystone.svg',
	'Gypsum Anhydrite': 'gypsum-anhydrite.svg',
	'Halite': 'halite.svg',
	'Lacustrine': 'lacustrine.svg',
	'Lava': 'lava.svg',
	'Limestone': 'limestone.svg',
	'Metavolcanics': 'metavolcanics.svg',
	'Mixed Marine': 'mixed_marine.svg',
	'No Data': 'no_data.svg',
	'Oolitic Limestone': 'oolitic_limestone.svg',
	'Pelagic Biogenic': 'pelagic_biogenic.svg',
	'Pelagic Marl': 'pelagic_marl.svg',
	'Reef Limestone': 'reef_limestone.svg',
	'Saline': 'saline.svg',
	'Sandstone': 'sandstone.svg',
	'Sandy Claystone': 'sandy_claystone.svg',
	'Sandy Limestone': 'sandy_limestone.svg',
	'Shallow Marine Carbonate': 'shallow-marine_carbonate.svg',
	'Shallow Marine Marl': 'shallow-marine_marl.svg',
	'Siliceous Chalk': 'siliceous_chalk.svg',
	'Siliceous Limestone': 'siliceous_limestone.svg',
	'Siltstone': 'siltstone.svg',
	'Soil': 'soil.svg',
	'Two Tone Beige': 'two_tone_beige.png',
	'Two Tone Blue': 'two_tone_blue.png',
	'Two Tone Gray': 'two_tone_gray.png',
	'Two Tone Olive Green': 'two_tone_olive_green.png',
	'Two Tone Red Green': 'two_tone_red_green.png',
	'Two Tone Red': 'two_tone_red.png',
	'Volcanic Ash': 'volcanic_ash.svg',
	'Volcanics': 'volcanics.svg'
}
