var transectApp = transectApp || {};
transectApp.VERTICAL_SCALE = 1;
transectApp.PIX_PER_MY = 30;
transectApp.WIDTH = 500;
transectApp.polygonFill = "#FFFF33";
transectApp.glowColor = "#FF0000 ";
transectApp.renderFill = "#66FF66";
transectApp.lineMouseOver = "#FF0000 ";
transectApp.lineMouseOut = "#000000";
transectApp.precision = 1; // rounding of to nearest percentage.
transectApp.steps = Math.round(100/transectApp.precision);